version: "3"
services:
  haproxy:
    build:
      context: ./haproxy/
      dockerfile: Dockerfile
    depends_on:
      - front
    links:
      - front
    ports:
      - "80:80"
      - "443:443"
      - "3001:3001"
  front:
    build:
      context: ./front/
      dockerfile: Dockerfile-prod
    volumes:
      - ./front/src:/usr/app/src
    ports:
      - "3000:3000"
  back:
    build:
      context: ./back/
      dockerfile: Dockerfile-dev
    volumes:
      - ./back/src:/usr/app/src
    ports:
      - "3002:3002"
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
