version: "3"
services:
  front:
    build:
      context: ./front/
      dockerfile: Dockerfile-dev
    volumes:
      - ./front/:/usr/app
    ports:
      - "3000:3000"
  back:
    build:
      context: ./back/
      dockerfile: Dockerfile-dev
    volumes:
      - ./back/:/usr/app
    ports:
      - "3002:3002"
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
