version: "3"
services:
  front:
    build: 
      context: ./front/app
      dockerfile: Dockerfile-dev
    volumes:
      - ./front/app:/usr/app
      - /usr/app/node_modules
    ports:
      - "3000:3000"
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: changeme
    volumes:
      - "/var/run/postgres/postgres.sock:/var/run/postgres/postgres.sock"
      - "dbdata:/var/lib/postgresql/data"

volumes:
  dbdata: